### PR TITLE
feat(license): relicense to Parity-6.0.0

### PR DESCRIPTION
**Pull request by zkat**
See also: https://paritylicense.com/

@passcod Can you 👍  if you agree with this license change? I noticed on Twitter you mentioned having a moral clause, but I'm uncomfortable doing that because I'm not sure it's as legally sound or enforceable.

tl;dr the Parity license is like the AGPL on steroids, and way easier to read. I highly recommend reading the whole thing.

This also includes a very cool [Patron license](https://blog.licensezero.com/2019/05/24/patron-license.html) for bypassing the copyleft requirements if you're $$paying up$$

/cc @kemitchell

### CODE REVIEW

**Comment by kemitchell** [comment]
I am tied up with family matters this weekend, but will have a look as soon as I can!

**Comment by passcod** [comment]
I'm going to go further and, as of this comment, reassign copyright
permanently over my past contributions to this project to Kat Marchán.

**Comment by zkat** [comment]
wow, thanks!

**Comment by nschonni** [comment]
Not sure if it's something you considered, but using a license that isn't recognized by OSI or FSF would turn away some places from being able to use it. It also looks like they're not going to submit it for review https://github.com/licensezero/parity-public-license/issues/39

**Comment by kemitchell** [comment]
@nschonni: Even if OSI or FSF did approve, many places—particularly proprietary software companies—would refuse to use Parity-licensed software. Because of what Parity says.

**Comment by zkat** [comment]
After thinking about it (and writing [an entire article on the subject](https://dev.to/zkat/a-system-for-sustainable-foss-11k9)), I've decided I'm not ready to use Parity on libraries and deal with the implications of that, so I'm closing this.

Most likely, I will be relicensing cacache under the [MPL](https://choosealicense.com/licenses/mpl-2.0/) instead, as a better balance (to me) between having a copyleft license and making the library easily usable by others.

**Comment by kemitchell** [comment]
@zkat if you're thinking about MPL, I'd love your feedback on [API Copyleft](https://apicopyleft.com/versions/1.0.0.html)!

**Pull request closed without merging**
