### PR TITLE
Added the feature flags for compilation without the async runtime. Fixes #64.

### LINKED ISSUE #64: Compilation error
I'm trying to use only the sync api, because I don't need the async one. So I don't want to pull the async runtime, and I copied the following content in my Cargo.toml, as the Docs.rs page said:
`cacache = { version = "12.0.0", default-features = false, features = ["mmap"] }`  
And I got the following error log: 
```
error[E0433]: failed to resolve: could not find `async_lib` in the crate root
   --> /home/kinire98/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cacache-12.0.0/src/index.rs:426:20
    |
426 |             crate::async_lib::remove_file(&bucket)
    |                    ^^^^^^^^^ could not find `async_lib` in the crate root

error[E0425]: cannot find function `find_async` in module `index`
   --> /home/kinire98/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cacache-12.0.0/src/get.rs:329:37
    |
329 |         if let Some(entry) = index::find_async(cache, key).await? {
    |                                     ^^^^^^^^^^ not found in `index`
    |
note: found an item that was configured out
   --> /home/kinire98/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cacache-12.0.0/src/index.rs:179:14
    |
179 | pub async fn find_async(cache: &Path, key: &str) -> Result<Option<Metadata>> {
    |              ^^^^^^^^^^

error[E0425]: cannot find function `find_async` in module `index`
   --> /home/kinire98/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cacache-12.0.0/src/get.rs:365:37
    |
365 |         if let Some(entry) = index::find_async(cache, key).await? {
    |                                     ^^^^^^^^^^ not found in `index`
    |
note: found an item that was configured out
   --> /home/kinire98/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cacache-12.0.0/src/index.rs:179:14
    |
179 | pub async fn find_async(cache: &Path, key: &str) -> Result<Option<Metadata>> {
    |              ^^^^^^^^^^

error[E0425]: cannot find function `open_async` in this scope
   --> /home/kinire98/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cacache-12.0.0/src/content/read.rs:166:22
    |
166 |     let mut reader = open_async(cache, sri.clone()).await?;
    |                      ^^^^^^^^^^ not found in this scope

error[E0433]: failed to resolve: use of undeclared type `AsyncReadExt`
   --> /home/kinire98/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cacache-12.0.0/src/content/read.rs:169:20
    |
169 |         let read = AsyncReadExt::read(&mut reader, &mut buf)
    |                    ^^^^^^^^^^^^ use of undeclared type `AsyncReadExt`

error[E0425]: cannot find function `delete_async` in this scope
   --> /home/kinire98/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cacache-12.0.0/src/index.rs:423:13
    |
423 |             delete_async(cache.as_ref(), key.as_ref()).await
    |             ^^^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0425, E0433.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `cacache` (lib) due to 6 previous errors

```
This is the neofetch information of my PC if it is useful:
```
                     ./o.                  
                   ./sssso-                ------------------ 
                 `:osssssss+-              OS: EndeavourOS Linux x86_64 
               `:+sssssssssso/.            Host: GF63 Thin 10SCSR REV:1.0 
             `-/ossssssssssssso/.          Kernel: 6.6.10-arch1-1 
           `-/+sssssssssssssssso+:`        Uptime: 4 hours, 36 mins 
         `-:/+sssssssssssssssssso+/.       Packages: 1085 (pacman), 8 (snap) 
       `.://osssssssssssssssssssso++-      Shell: bash 5.2.21 
      .://+ssssssssssssssssssssssso++:     Resolution: 1920x1080, 1920x1080 
    .:///ossssssssssssssssssssssssso++:    DE: Xfce 4.18 
  `:////ssssssssssssssssssssssssssso+++.   WM: Xfwm4 
`-////+ssssssssssssssssssssssssssso++++-   WM Theme: Default 
 `..-+oosssssssssssssssssssssssso+++++/`   Theme: Adwaita-dark [GTK2], Arc-Dark [GTK3] 
   ./++++++++++++++++++++++++++++++/:.     Icons: Qogir-dark [GTK2/3] 
  `:::::::::::::::::::::::::------``       Terminal: xfce4-terminal 
                                           Terminal Font: Source Code Pro 10 
                                           CPU: Intel i7-10750H (12) @ 5.000GHz 
                                           GPU: Intel CometLake-H GT2 [UHD Graphics] 
                                           GPU: NVIDIA GeForce GTX 1650 Ti Mobile 
                                           Memory: 4150MiB / 31917MiB 

```
I don't know if I have to change something for it to work. If I just write:
`cacache = "12.0.0"`
works normally, but imports the whole async runtime.

### PR DESCRIPTION
**Pull request by kinire98**
Here is the feature flags added for the #64 issue. I tested it and it compiles fine.  
I forgot to create a new branch, hope there is no problem in that.

### CODE REVIEW

**Comment by zkat** [comment]
Looks like you need to add it to an import now, since it's not getting used anymore :)

**Comment by kinire98** [comment]
I don't understand. If it's not used in the library, shouldn't it be removed?

**Comment by kinire98** [comment]
Maybe this last commit, is unwanted, because I changed the default features.

**Comment by kinire98** [comment]
nvm. I found another module. Sorry for the repetition.

**Comment by zkat** [comment]
This is released now as part of 13.0.0

**Pull request merged**
