### PR TITLE
add some tests

### PR DESCRIPTION
**Pull request by rickycodes**
re: #3 

I know this isn't quite right because i am not that familiar with the API, but it gets the ball rolling. Also is there a way to use a lib without making it a dependency of itself? that part feels wrong

### CODE REVIEW

**Comment by rickycodes** [comment]
thanks for getting me sorted with `crate::` that makes _way_ more sense

I kinda started building a test for `entry` and made some **realizations**:

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn all() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().to_owned();
        crate::put::data(&dir, "key", b"my-data").unwrap();
        let data = crate::get::read(&dir, "key").unwrap();
        assert_eq!(data, b"my-data");
        crate::rm::all(&dir).unwrap();
        // panics on unwrap
        let new_data = crate::get::read(&dir, "key").unwrap_or([].to_vec());
        assert_eq!(new_data.len(), 0);
    }

    #[test]
    fn entry() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().to_owned();
        crate::put::data(&dir, "key", b"my-data").unwrap();
        let data = crate::get::read(&dir, "key").unwrap();
        assert_eq!(data, b"my-data");

        crate::rm::entry(&dir, "key").unwrap();

        let new_data = crate::get::read(&dir, "key").unwrap_or([].to_vec());
        println!("{:?}", new_data);
        assert_eq!(new_data.len(), 0);
    }
}
```

both tests are essentially the same now, which seems not quite right... is there a better way to test these two particular methods without just checking to see if it _not_ panics on read? also realizing they now have the same setup so that should maybe be abstracted into some single method

I'm going to see if i can find some additional examples of things so i can get some better ideas

**Comment by zkat** [comment]
instead of using `unwrap_or()`, I would actually test the returned value itself. I would also use the `info` and `hash_exists` functions in this case to be more specific about what we're checking for:

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn all() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().to_owned();
        crate::put::data(&dir, "key", b"my-data").unwrap();

        crate::rm::all(&dir).unwrap();

        let new_entry = crate::get::info(&dir, "key").unwrap();
        assert_eq!(new_entry, None);

        let data_exists = crate::get::hash_exists(&dir, &sri);
        assert_eq!(data_exists, false);
    }

    #[test]
    fn entry() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().to_owned();
        let sri = crate::put::data(&dir, "key", b"my-data").unwrap();

        crate::rm::entry(&dir, "key").unwrap();

        let new_entry = crate::get::info(&dir, "key").unwrap();
        assert_eq!(new_entry, None);

        let data_exists = crate::get::hash_exists(&dir, &sri);
        assert_eq!(data_exists, true);
    }
}
```

**Comment by rickycodes** [comment]
awesome! I see that you've updated docs a bit, so I may go ahead and add some additional tests for some of that stuff (providing they're still needed). thanks for letting me contribute! :)

**Comment by zkat** [comment]
Please go ahead! As always, let me know if you need any help :)

**Pull request merged**
